FROM debian:stretch
MAINTAINER Azleal

#debian版本,可以修改.需与FROM版本一致
ARG VER=stretch

#阿里源镜像
RUN echo deb http://mirrors.aliyun.com/debian/ ${VER} main non-free contrib > /etc/apt/sources.list \
	&& echo deb-src http://mirrors.aliyun.com/debian/ ${VER} main non-free contrib >> /etc/apt/sources.list \
	&& echo deb http://mirrors.aliyun.com/debian-security ${VER}/updates main >> /etc/apt/sources.list \
	&& echo deb-src http://mirrors.aliyun.com/debian-security ${VER}/updates main >> /etc/apt/sources.list \
	&& echo deb http://mirrors.aliyun.com/debian/ ${VER}-updates main non-free contrib >> /etc/apt/sources.list \
	&& echo deb-src http://mirrors.aliyun.com/debian/ ${VER}-updates main non-free contrib >> /etc/apt/sources.list \
	&& echo deb http://mirrors.aliyun.com/debian/ ${VER}-backports main non-free contrib >> /etc/apt/sources.list \
	&& echo deb-src http://mirrors.aliyun.com/debian/ ${VER}-backports main non-free contrib >> /etc/apt/sources.list \
	&& apt-get update

#编码
RUN apt-get install -y \
        locales \
&& rm -rf /var/lib/apt/lists/* \
&& localedef -i zh_CN -c -f UTF-8 -A /usr/share/locale/locale.alias zh_CN.UTF-8
ENV LANG zh_CN.UTF-8

#时区设置
ENV TZ=Asia/Shanghai

#安装新程序使用以下命令
#RUN apt-get update && apt-get install -y telnet && rm -rf /var/lib/apt/lists/*
